### ISSUE TITLE
GRB color order

### ISSUE THREAD

**Issue by BlinkyStitt** [kalkyl/ws2812-async#2]
I have some neopixels that are GRB instead of RGB. I can make an iterator that swaps the R and G, but I think a type state would work well for this.

related: https://github.com/smart-leds-rs/ws2812-spi-rs/issues/7

**Comment by kalkyl** [comment]
Good idea! I think i would prefer implementing using a feature gate instead

**Comment by BlinkyStitt** [comment]
But only some of my strips are GRB. Others are RGB. If it's a feature gate, I couldn't use both in the same project.

**Comment by okhsunrog** [comment]
@kalkyl I think this issue can be closed now
